### ISSUE TITLE
Python 3.x compatibility

### ISSUE THREAD

**Issue by ronnix** [RonenNess/html_validator#2]
In Python 2.7:
```python
>>> import html_validator
```

In Python 3.6:
```python
>>> import html_validator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/html_validator/__init__.py", line 10, in <module>
    from html_validator import validate, MissingValidatorOrJava, MissingHtmlFile, ValidationError
ImportError: cannot import name 'validate'
```

**Comment by RonenNess** [comment]
Hi @ronnix ,

I wrote it for py2.7 it doesn't work on 3 (tbh not sure why, its some weird import issue but I didn't look much into it).

Anyway you can just copy the code and it should work, as seen here:
https://github.com/RonenNess/html_validator/issues/1

If you want to make a PR for py3 that would be appreciated.

Thanks :)
