### ISSUE TITLE
validate not defined.

### ISSUE THREAD

**Issue by Beyarz** [RonenNess/html_validator#6]
When running the script:

    try:
    import os
    from html_validator import validate
    except(ImportError):
    print("Could not import lib.")
    errors = validate("index.html")
    for err in errors:
    print("Type: %s, File: %s, Line: %d, Description: %s" % (err.type, err.file, err.line, err.description))

I get this error:
    
    Traceback (most recent call last):
    File "validate.py", line 13, in <module>
    errors = validate("index.html")
    NameError: name 'validate' is not defined

Can't figure out why.

**Comment by RonenNess** [comment]
Your error says line 13 but in your code its line 6. This tells me its not the same code.
Its probably something in your code / you are not really running what you think you're running.

Please open a Python shell and run the following commands:

    >>> from html_validator import validate
    >>> errors = validate("index.html")

Without anything else - if that doesn't work - please reopen the issue.
Thanks! :)

**Comment by Beyarz** [comment]
The code was same, I just removed a couple of lines that were sensitive before posting it in here.
I managed to resolve the issue anyways.
I executed the script with python 3.7 instead of 2.7.
That was the issue, took me some time to realize that.

**Comment by Beyarz** [comment]
A warning would definitely be useful for cases like these.
